---
# Docker configuration (for geerlingguy.docker role)
docker_add_repo: true
docker_install_compose: true
docker_compose_version: "v2.32.1"
docker_users:
  - "{{ ansible_user }}"

# Domain configuration
domain_name: example.com
email: admin@example.com

# DNS provider for acme.sh (Change to your DNS provider)
dns_provider: cloudflare
dns_api_token: your_dns_api_token_here

# HAProxy Configuration
haproxy_container_name: haproxy
haproxy_image: haproxy:latest
haproxy_config_dir: /etc/haproxy
haproxy_port: 443
haproxy_http_port: 8080  # HAProxy port for HTTP proxy
haproxy_stats_port: 8404  # HAProxy stats port for monitoring

# Xray Configuration
xray_container_name: xray
xray_image: teddysun/xray:latest
xray_config_dir: /etc/xray
xray_cert_dir: /etc/xray/certs
xray_port: 443
xray_path: "/xray"
xray_lego_dir: /etc/lego

# Xray Agent Configuration
xray_agent_enabled: true                # Set to false to disable agent-based health checks
xray_agent_port: 8192                   # Port for agent health checks
xray_agent_timeout: 5                   # Timeout for external connectivity checks (seconds)
xray_agent_success_threshold: 3         # Number of successful checks needed to mark server as up
xray_agent_test_sites: "https://www.google.com,https://www.cloudflare.com,https://www.github.com"  # Sites to test connectivity

# HTTP Proxy Configuration
xray_http_enabled: true  # Set to false to disable HTTP proxy
xray_http_port: 8080     # HTTP proxy port
xray_http_user: "username"
xray_http_pass: "password"

# Monitoring Configuration
monitoring_enabled: true  # Set to false to disable monitoring
prometheus_container_name: prometheus
prometheus_image: prom/prometheus:latest
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_port: 9090

grafana_container_name: grafana
grafana_image: grafana/grafana:latest
grafana_config_dir: /etc/grafana
grafana_data_dir: /var/lib/grafana
grafana_provisioning_dir: /etc/grafana/provisioning
grafana_port: 3000
grafana_admin_password: admin  # Change this to a secure password

exporter_config_dir: /etc/exporters
node_exporter_image: prom/node-exporter:latest
haproxy_exporter_image: prom/haproxy-exporter:latest

# Xray Client Configuration - Add your clients here
xray_clients:
  - id: "11111111-1111-1111-1111-111111111111"
    email: "client1@example.com"
    flow: "xtls-rprx-vision"
  - id: "22222222-2222-2222-2222-222222222222"
    email: "client2@example.com"
    flow: "xtls-rprx-vision"
  # Add more clients as needed