---
- name: Configure HAProxy server
  hosts: haproxy
  become: true
  roles:
    - geerlingguy.docker
    - common
    - haproxy

- name: Configure Xray main servers
  hosts: xray_main
  become: true
  roles:
    - geerlingguy.docker
    - common
    - xray

- name: Configure Xray backup servers
  hosts: xray_backup
  become: true
  roles:
    - geerlingguy.docker
    - common
    - xray

# Setup monitoring (conditionally)
- name: Deploy monitoring stack on HAProxy server
  hosts: haproxy
  become: true
  roles:
    - role: monitoring
      tags: monitoring

# Install exporters on all servers for metrics collection
- name: Install monitoring exporters on all servers
  hosts: all
  become: true
  tasks:
    - name: Include exporter tasks
      include_tasks: roles/monitoring/tasks/exporters.yml
      when: monitoring_enabled | default(true)
      tags: monitoring

- name: Validate deployment on servers
  hosts: all
  become: true
  roles:
    - validation

- name: Validate end-to-end connectivity
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Include connectivity validation tasks
      include_tasks: roles/validation/tasks/connectivity.yml

