---
- name: Configure HAProxy server
  hosts: haproxy
  become: true
  roles:
    - geerlingguy.docker
    - common
    - haproxy

- name: Configure Xray main servers
  hosts: xray_main
  become: true
  roles:
    - geerlingguy.docker
    - common
    - xray

- name: Configure Xray backup servers
  hosts: xray_backup
  become: true
  roles:
    - geerlingguy.docker
    - common
    - xray

- name: Validate deployment on servers
  hosts: all
  become: true
  roles:
    - validation

- name: Validate end-to-end connectivity
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Include connectivity validation tasks
      include_tasks: roles/validation/tasks/connectivity.yml

